### ISSUE TITLE
Create Dev Blog

### ISSUE THREAD

**Issue by JamesVpog** [suasuasuasuasua/Paralander#6]
https://github.com/jekyll/minima?tab=readme-ov-file

look at _config.yml and figure it out

**Comment by JamesVpog** [comment]
sua to also write blog posts

**Comment by suasuasuasuasua** [comment]
- [Website](https://beautifuljekyll.com/2020-02-28-sample-markdown/)
- [Repo](https://github.com/daattali/beautiful-jekyll)
- [Config yaml](https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml)

**Comment by suasuasuasuasua** [comment]
For now, we've basically gotten this issue resolved. There are a few things to clean up page-wise, but smaller issues can be created to address them. For instance,

- write a real first post
- write the about me blurbs for each of us
- think more about the organization of the pages and images in the `assets/` folder in case things get messy
