### ISSUE TITLE
Learn basic unity tutorials (before physics tutorials)

### ISSUE THREAD

**Issue by JamesVpog** [suasuasuasuasua/Paralander#7]
- [x] https://learn.unity.com/pathway/unity-essentials 
- [x] https://learn.unity.com/pathway/junior-programmer

First physics:
- [ ] https://learn.unity.com/tutorial/lesson-1-forces#

**Comment by suasuasuasuasua** [comment]
Need to do this basic research before #4 can be realistically started.

**Comment by JamesVpog** [comment]
got the first Badge in unity essentials:
- https://learn.unity.com/u/65bd6344edbc2a3bc8ae8f11
